name: Audit

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    audit:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.23.0

            - name: Verify Dependencies
              run: go mod verify

            - name: Run go vet
              run: go vet ./...

            - name: Install staticcheck
              run: go install honnef.co/go/tools/cmd/staticcheck@2024.1.1

            - name: Run static check
              run: staticcheck ./...

            - name: Run tests
              run: go test -race ./...
