name: Deploy Image to GHCR

on:
    workflow_run:
        workflows: ["Audit"]
        types:
            - completed

permissions:
    packages: write
    contents: read

jobs:
    push-image:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GH_TOKEN }}

            - name: Build and push image
              run: |
                  docker build --tag ghcr.io/${{ github.repository }}:latest .
                  docker push ghcr.io/${{ github.repository }}:latest
